POST https://flannel-hockey-38964.herokuapp.com/api/owners
Content-Type: application/json

{
    "firstName": "Zoe",
    "lastName": "Manning",
    "age": 21
}


###

POST https://flannel-hockey-38964.herokuapp.com/api/manufacturers
Content-Type: application/json

{
    "name": "Hyundai"
}

###

POST https://flannel-hockey-38964.herokuapp.com/api/cars
Content-Type: application/json

{
    "model": "Accent",
    "manufacturer_id": 1
}


###

POST https://flannel-hockey-38964.herokuapp.com/api/individualcars
Content-Type: application/json

{
    "color": "Blue",
    "year": "2011",
    "vin": "1234556342343",
    "carId": 1,
    "ownerId": 1
}

###

GET https://flannel-hockey-38964.herokuapp.com/api/individualcars


###

GET http://localhost:3001/


